---
#Health monitor properties
trustStorePath: src/main/resources/client-truststore.jks
# Security
encryptionKey: ThisIsSpartaThisIsSparta
#APIM Creadentials
apimUsername: admin
apimPassword: 07WfylTarjY=
#APIM configs
apimHost: localhost
apimPort: 9763
apimGatewayPort: 8243
clientName: myTestClient1
applicationName: MyHealthMonitorTestApplication
applicationTier: Unlimited
applicationAuthorizedDomains: ALL
applicationKeyType: PRODUCTION
applicationKeyValidityTime: -1
#APIs
apis:
    CalculatorAPI:
        apiContext: calc/1.0
        apiVersion: 1.0
        apiProvider: admin
        apiTier: Unlimited
        apiResources:
            [add, GET]:
                parameters:
                    x: 5
                    y: 10
            [divide, GET]:
                parameters:
                    x: 255
                    y: 15
    PhoneVerification:
        apiContext: phoneverify/1.0.0
        apiVersion: 1.0.0
        apiProvider: admin
        apiTier: Unlimited
        apiResources:
            [CheckPhoneNumber, GET]:
                parameters:
                    PhoneNumber: 2342
                    LicenseKey: 2433242
#    PhoneVerification:
#                apiMethod: GET
#                apiUrl: https://localhost:8243/phoneverify/1.0.0/wrongQuery
#                apiVersion: 1.0.0
#                apiProvider: admin
#                apiTier: Unlimited
#                parameters:
# DAS credentials
dasUsername: admin
dasPassword: 07WfylTarjY=
# DAS configurations
# Use HTTPS endpoint
dasReceiverUrl: https://localhost:9460/endpoints/newHealthMonitorReceiver
...
