---
#APIM Creadentials
apimUsername: admin
apimPassword: admin
#APIM configs
apimHost: localhost
apimPort: 9763
applicationName: MyHealthMonitorTestApplication
applicationTier: Unlimited
applicationAuthorizedDomains: ALL
applicationKeyType: PRODUCTION
applicationKeyValidityTime: -1
#APIs
apis:
    CalculatorAPI:
        apiMethod: GET
        apiUrl: https://localhost:8243/calc/1.0/add
        apiVersion: 1.0
        apiProvider: admin
        apiTier: Unlimited
        parameters:
            x: 5
            y: 10
    PhoneVerification:
            apiMethod: GET
            apiUrl: https://localhost:8243/phoneverify/1.0.0/CheckPhoneNumber
            apiVersion: 1.0.0
            apiProvider: admin
            apiTier: Unlimited
            parameters:
                PhoneNumber: 2342
                LicenseKey: 2433242
#    PhoneVerification:
#                apiMethod: GET
#                apiUrl: https://localhost:8243/phoneverify/1.0.0/wrongQuery
#                apiVersion: 1.0.0
#                apiProvider: admin
#                apiTier: Unlimited
#                parameters:
# DAS credentials
dasUsername: admin
dasPassword: admin
# DAS configurations
# Use HTTPS endpoint
dasReceiverUrl: https://localhost:9460/endpoints/healthMonitorIntervals_1_Receiver
...
