---
#APIM Creadentials
apimUsername: admin
apimPassword: admin
#APIM configs
apimHost: localhost
apimPort: 9763
applicationName: MyHealthMonitorTestApplication
applicationTier: Unlimited
applicationAuthorizedDomains: ALL
applicationKeyType: PRODUCTION
applicationKeyValidityTime: -1
#APIs
apis:
    CalculatorAPI:
        apiMethod: GET
        apiUrl: https://localhost:8243/calc/1.0/add
        apiVersion: 1.0
        apiProvider: admin
        apiTier: Unlimited
        parameters:
            x: 5
            y: 10
# DAS credentials
dasUsername: admin
dasPassword: admin
# DAS configurations
# Use HTTPS endpoint
dasReceiverUrl: https://localhost:9460/endpoints/healthMonitorReceiver
...
